import Head from 'next/head'
import { Inter } from 'next/font/google'

import Loader from '@app/shared/Loader'
import styles from '@app/styles/Home.module.css'

import toast from 'react-hot-toast';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Loader show />
        <button onClick={() => toast.success('Toma')}>
          Toast Me
        </button>
      </main>
    </>
  )
}
